name: build

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
    tags: ["v[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  jvm-tests:
    name: JVM (scala ${{ matrix.scala }}, jvm ${{ matrix.java }})
    strategy:
      fail-fast: true      
      matrix:
        os: [ubuntu-20.04]
        java: [8, 11]
#        scala: [2.12.14, 2.13.6, 3.0.2]
        scala: [2.12.14, 2.13.6]
        command: ["ci-jvm"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: sbt ++${{ matrix.scala }} ${{ matrix.command }}
        run: |
          ./.github/scripts/build.sh
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SBT_COMMAND: ${{ matrix.command }}

  package-tests:
    name: Package (scala ${{ matrix.scala }}, jvm ${{ matrix.java }})
    strategy:
      fail-fast: true      
      matrix:
        os: [ubuntu-20.04]
        java: [11]
#        scala: [2.12.14, 2.13.6, 3.0.2]
        scala: [2.12.14, 2.13.6]
        command: [ci-package]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: sbt ++${{ matrix.scala }} ${{ matrix.command }}
        run: |
          ./.github/scripts/build.sh
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SBT_COMMAND: ${{ matrix.command }}

  #-----------------------------------------------------------------------------------
  # Publishing tasks
  #-----------------------------------------------------------------------------------

  publish_sonatype:
    name: Publish to GitHub Packages
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [ jvm-tests, package-tests ]
    strategy:
      fail-fast: true      
      max-parallel: 1
      matrix:
        command: [ci-release]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.8"

      - name: sbt publish
        run: |
          git fetch --tags
          sbt +clean publish
